// DEFINITION - CARD COLOR:
import 'package:bmi_calculator/enums/gender_enum.dart';
import 'package:flutter/material.dart';

// GENERAL - TEXTS
const DEFAULT_CENTIMETERS_TEXT = 'cm';

// DEFINITION - MATERIAL APP:
const CUSTOM_THEME_PRIMARY_COLOR = Color(0xFF0E1020);
const CUSTOM_THEME_SCAFFOLD_BACKGROUND_COLOR = Color(0xFF0E1020);

// DEFINITION - CUSTOM ICON BOX:
const ICON_BOX_ICON_SIZE = 60.0;
const ICON_BOX_SPACE = 15.0;

// DEFINITION - APP:
const APP_TITLE = 'BMI Calculator';

// DEFINITION - CUSTOM CARD:
const CUSTOM_CARD_DEFAULT_GENDER = Gender.MALE;
const CUSTOM_CARD_DEFAULT_HEIGHT = 150;
const CUSTOM_CARD_DEFAULT_WEIGHT = 60;
const CUSTOM_CARD_DEFAULT_AGE = 25;
const CUSTOM_CARD_MARGIN = 15.0;
const CUSTOM_CARD_BORDER_RADIUS = 10.0;
const CUSTOM_CARD_ACTIVE_COLOR = Color(0xFF1D1E33);
const CUSTOM_CARD_INACTIVE_COLOR = Color(0xFF111328);
const CUSTOM_CARD_MALE_TEXT = 'MALE';
const CUSTOM_CARD_FEMALE_TEXT = 'FEMALE';
const CUSTOM_CARD_HEIGHT_TEXT = 'HEIGHT';
const CUSTOM_CARD_WEIGHT_TEXT = 'WEIGHT';
const CUSTOM_CARD_AGE_TEXT = 'AGE';

const CUSTOM_CARD_LABEL_TEXT_STYLE = TextStyle(
  color: Color(0xFF8D8E98),
  fontSize: 15.0
);

const CUSTOM_CARD_VALUE_TEXT_STYLE = TextStyle(
  fontSize: 35.0,
  fontWeight: FontWeight.w900
);

// DEFINITION - BOTTOM BUTTON:
const BOTTOM_BUTTON_COLOR = Color(0xFFEB1555);
const BOTTOM_BUTTON_MARGIN_TOP = 10.0;
const BOTTOM_BUTTON_HEIGHT = 80.0;
const BOTTOM_BUTTON_WIDTH = double.infinity;
const BOTTOM_BUTTON_CALCULATE_TEXT = 'CALCULATE';
const BOTTOM_BUTTON_RECALCULATE_TEXT = 'RE-CALCULATE';

const BOTTOM_BUTTON_TEXT_STYLE = TextStyle(
    fontSize: 25.0,
    fontWeight: FontWeight.bold
);

// DEFINITION - CUSTOM SLIDER:
const CUSTOM_SLIDER_ACTIVE_TRACK_COLOR = Colors.white;
const CUSTOM_SLIDER_INACTIVE_TRACK_COLOR = Color(0xFF8D8E98);
const CUSTOM_SLIDER_TRACK_HEIGHT = 1.0;
const CUSTOM_SLIDER_THUMB_SHAPE_RADIUS = 12.0;
const CUSTOM_SLIDER_THUMB_COLOR = Color(0xFFEB1555);
const CUSTOM_SLIDER_OVERLAY_SHAPE_RADIUS = 24.0;
const CUSTOM_SLIDER_OVERLAY_COLOR = Color(0x29EB1555);

// DEFINITION - RESULT:
const RESULT_TITLE_TEXT = 'Your Result';
const RESULT_TITLE_STYLE = TextStyle(
    fontSize: 35.0,
    fontWeight: FontWeight.bold
);

// DEFINITION - RESULT CARD:
const RESULT_CARD_TITLE_STYLE = TextStyle(
    fontSize: 18.0,
    fontWeight: FontWeight.bold,
    color: Color(0xFF24D876)
);

const RESULT_CARD_VALUE_STYLE = TextStyle(
    fontSize: 100.0,
    fontWeight: FontWeight.bold
);

// BMI:
const BMI_CLASSIFICATION_UNDERWEIGHT = 'UNDERWEIGHT';
const BMI_CLASSIFICATION_NORMAL = 'NORMAL';
const BMI_CLASSIFICATION_OVERWEIGHT = 'OVERWEIGHT';
const BMI_CLASSIFICATION_OBESE = 'OBESE';
const BMI_CLASSIFICATION_EXTREMELY_OBESE = 'EXTREMELY OBESE';

